name: Deploy to server (build on host)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            APP_DIR=${{ secrets.SERVER_DIR }}
            if [ ! -d "$APP_DIR/.git" ]; then
              mkdir -p "$APP_DIR"
              git clone ${{ secrets.REPO_CLONE_URL }} "$APP_DIR"
            fi
            cd "$APP_DIR"
            git fetch --all
            git reset --hard origin/main

            docker compose down || true

            docker compose up -d --build

            docker image prune -f
