name: Build & Deploy on self-hosted

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted   # ewentualnie: [self-hosted, linux, x64, docker]
    steps:
      - name: Checkout merged commit (or main on manual run)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || 'refs/heads/main' }}

      # Jeśli docker-compose.yml leży w podkatalogu, dodaj: working-directory: ./subdir do kolejnych kroków

      - name: Build & start with Docker Compose
        run: |
          set -Eeuo pipefail
          docker compose up -d --build --remove-orphans

      - name: Prune old images (best-effort)
        run: docker system prune -af || true
